from __future__ import annotations

from datetime import UTC, datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

ProviderType = Literal["aws", "azure", "gcp", "k8s"]
ProviderStatus = Literal["pending", "active", "error", "disabled"]


class ProviderConfig(BaseModel):
    """Stored configuration for a connected cloud provider (no secrets)."""

    key: str
    provider: ProviderType
    display_name: str
    account_id: str | None = None
    subscription_id: str | None = None
    project_id: str | None = None
    cluster_name: str | None = None
    regions: list[str] = Field(default_factory=list)
    enabled: bool = True
    status: ProviderStatus = "pending"
    # Which credential method was used at registration time (informational, no secrets)
    credential_type: str = "ambient"
    # AWS cross-account role — not a credential (no secret), safe to store in ArangoDB
    role_arn: str | None = None
    # External ID generated by Ogum per tenant-provider pair (confused deputy protection)
    external_id: str | None = None
    # Azure: tenant/client IDs are not secrets — safe to store for informational purposes
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    last_discovery_at: str | None = None
    last_discovery_job_id: str | None = None
    # Written by POST /{id}/test-connection — last live probe outcome (detail truncated)
    last_health_check_at: str | None = None
    last_health_result: str | None = None
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())


class ProviderRegisterRequest(BaseModel):
    provider: ProviderType
    display_name: str
    account_id: str | None = None
    subscription_id: str | None = None
    project_id: str | None = None
    cluster_name: str | None = None
    regions: list[str] = Field(default_factory=list)  # empty = all available regions
    validate_connection: bool = True
    # AWS — option A: cross-account IAM role (recommended for multi-account)
    role_arn: str | None = None
    # AWS — option B: static access keys (stored in Vault only — US-06.11/ADR-015)
    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    # Azure Service Principal credentials (client_secret stored in Vault only)
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    azure_client_secret: str | None = None
    # GCP Service Account JSON (stored in Vault only)
    gcp_service_account_json: dict[str, Any] | None = None
    # Kubernetes external cluster kubeconfig (stored in Vault only)
    kubeconfig: dict[str, Any] | None = None


class ProviderUpdateRequest(BaseModel):
    display_name: str | None = None
    regions: list[str] | None = None
    enabled: bool | None = None
    # Non-secret credential metadata — safe to store in tenant_config
    role_arn: str | None = None
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    # Secrets live in Vault (US-06.11); the document carries only the
    # credentials_vault_path/_version references and is never returned by API responses
    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    azure_client_secret: str | None = None
    gcp_service_account_json: dict[str, Any] | None = None
    kubeconfig: dict[str, Any] | None = None


class ProviderRegisterResponse(BaseModel):
    provider_id: str
    discovery_job_id: str | None = None
    message: str


class DiscoverRequest(BaseModel):
    """Optional body for POST /{id}/discover.

    Allows re-providing credentials for providers registered with
    credential_type='static' / 'service_principal' / 'service_account' / 'kubeconfig'.
    Credentials passed here are persisted to Vault (US-06.11) and resolved by the
    task in the worker — never carried in the Celery payload (US-06.12).
    Omit the body (or all fields) to use ambient worker credentials / stored role_arn.
    """

    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    azure_client_secret: str | None = None
    gcp_service_account_json: dict[str, Any] | None = None
    kubeconfig: dict[str, Any] | None = None


class DiscoverResponse(BaseModel):
    provider_id: str
    discovery_job_id: str
    message: str


ProviderHealthLevel = Literal["healthy", "degraded", "failed"]


class ProviderHealth(BaseModel):
    """Connection health for one connected provider.

    `health` is derived either from stored signals (`live=False`, cheap — used by
    GET /{id}/health when rendering many cards) or from a real credential probe
    (`live=True`, POST /{id}/test-connection).
    """

    provider_id: str
    health: ProviderHealthLevel
    status: ProviderStatus
    enabled: bool
    reason: str | None = None
    detail: str | None = None
    latency_ms: int | None = None
    last_discovery_at: str | None = None
    checked_at: str | None = None
    live: bool = False
