from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

ProviderType = Literal["aws", "azure", "gcp", "k8s"]
ProviderStatus = Literal["pending", "active", "error", "disabled"]


class ProviderConfig(BaseModel):
    """Stored configuration for a connected cloud provider (no secrets)."""

    key: str
    provider: ProviderType
    display_name: str
    account_id: str | None = None
    subscription_id: str | None = None
    project_id: str | None = None
    cluster_name: str | None = None
    regions: list[str] = Field(default_factory=list)
    enabled: bool = True
    status: ProviderStatus = "pending"
    # Which credential method was used at registration time (informational, no secrets)
    credential_type: str = "ambient"
    # AWS cross-account role — not a credential (no secret), safe to store in ArangoDB
    role_arn: str | None = None
    # External ID generated by Ogum per tenant-provider pair (confused deputy protection)
    external_id: str | None = None
    # Azure: tenant/client IDs are not secrets — safe to store for informational purposes
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    last_discovery_at: str | None = None
    last_discovery_job_id: str | None = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ProviderRegisterRequest(BaseModel):
    provider: ProviderType
    display_name: str
    account_id: str | None = None
    subscription_id: str | None = None
    project_id: str | None = None
    cluster_name: str | None = None
    regions: list[str] = Field(default_factory=lambda: ["us-east-1"])
    validate_connection: bool = True
    # AWS — option A: cross-account IAM role (recommended for multi-account)
    role_arn: str | None = None
    # AWS — option B: static access keys (dev only, never stored in ArangoDB)
    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    # Azure Service Principal credentials (client_secret NOT stored — ephemeral)
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    azure_client_secret: str | None = None
    # GCP Service Account JSON (NOT stored — ephemeral)
    gcp_service_account_json: dict | None = None
    # Kubernetes external cluster kubeconfig (NOT stored — ephemeral)
    kubeconfig: dict | None = None


class ProviderUpdateRequest(BaseModel):
    display_name: str | None = None
    regions: list[str] | None = None
    enabled: bool | None = None
    # Non-secret credential metadata — safe to store in tenant_config
    role_arn: str | None = None          # AWS cross-account role ARN (empty string clears it)
    azure_tenant_id: str | None = None   # Azure AAD tenant ID
    azure_client_id: str | None = None   # Azure App Registration client ID


class ProviderRegisterResponse(BaseModel):
    provider_id: str
    discovery_job_id: str | None = None
    message: str


class DiscoverRequest(BaseModel):
    """Optional body for POST /{id}/discover.

    Allows re-providing ephemeral credentials for providers registered with
    credential_type='static' / 'service_principal' / 'service_account' / 'kubeconfig'.
    Credentials passed here are forwarded to the task and never stored.
    Omit the body (or all fields) to use ambient worker credentials / stored role_arn.
    """
    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    azure_client_secret: str | None = None
    gcp_service_account_json: dict | None = None
    kubeconfig: dict | None = None


class DiscoverResponse(BaseModel):
    provider_id: str
    discovery_job_id: str
    message: str
