from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class SoftwarePackage(BaseModel):
    name: str
    version: str
    cve_ids: list[str] = Field(default_factory=list)
    filesystem_path: str | None = None


class SoftwareLicense(BaseModel):
    license_id: str
    category: Literal["permissive", "copyleft", "weak_copyleft", "unknown"]
    deprecated: bool
    package_count: int


class SoftwareInventoryResponse(BaseModel):
    """Software Inventory sub-tabs (US-14.06).

    Installed Packages and Licenses are derived from the CycloneDX SBOM already
    generated by Side-Scanning (Epic 03). Applications and Running Services have no
    data source anywhere in the platform yet — `*_available=False` signals the
    frontend to render an explicit "not available yet" state instead of fabricated
    data, matching the precedent set for other un-wired tabs in Epic 14 Sprint 2.
    """

    resource_key: str
    sbom_generated_at: str | None = None
    installed_packages: list[SoftwarePackage] = Field(default_factory=list)
    licenses: list[SoftwareLicense] = Field(default_factory=list)
    applications_available: bool = False
    running_services_available: bool = False
